// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsr6Gwkfc5h6fiOkxHko0Ep27R5mCeyzU',
    appId: '1:392472105027:web:213b319de58820f4a7c4f6',
    messagingSenderId: '392472105027',
    projectId: 'rentlyapp-37b34',
    authDomain: 'rentlyapp-37b34.firebaseapp.com',
    storageBucket: 'rentlyapp-37b34.firebasestorage.app',
    measurementId: 'G-GSZGL8TGW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp2spXhnYS4JgpzSKO2lCn0FW3gf4WH28',
    appId: '1:392472105027:android:c23c98b1464f87efa7c4f6',
    messagingSenderId: '392472105027',
    projectId: 'rentlyapp-37b34',
    storageBucket: 'rentlyapp-37b34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP4wi8keAW5Odmfml-rVF17_MQOhShpjU',
    appId: '1:392472105027:ios:cca6e2b719f8f4a8a7c4f6',
    messagingSenderId: '392472105027',
    projectId: 'rentlyapp-37b34',
    storageBucket: 'rentlyapp-37b34.firebasestorage.app',
    iosBundleId: 'com.example.rentlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP4wi8keAW5Odmfml-rVF17_MQOhShpjU',
    appId: '1:392472105027:ios:cca6e2b719f8f4a8a7c4f6',
    messagingSenderId: '392472105027',
    projectId: 'rentlyapp-37b34',
    storageBucket: 'rentlyapp-37b34.firebasestorage.app',
    iosBundleId: 'com.example.rentlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsr6Gwkfc5h6fiOkxHko0Ep27R5mCeyzU',
    appId: '1:392472105027:web:0a500cded1871e6ba7c4f6',
    messagingSenderId: '392472105027',
    projectId: 'rentlyapp-37b34',
    authDomain: 'rentlyapp-37b34.firebaseapp.com',
    storageBucket: 'rentlyapp-37b34.fir ebasestorage.app',
    measurementId: 'G-DR1KQHWN0D',
  );
}
